### 셀러 상품 등록
POST http://localhost:8081/seller/product
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0VUpLVU5CTjFabGY3QkV5N2FPZmVTYjJRWktxRGhScnl6MXl5dHZpWkUwPSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgxMTg5MjY3LCJleHAiOjE2ODExOTI4Njd9.Dp1aqmDIIxmQPyaghQ1zMxDrRJU72pYBuSqhUPGZV80

{
  "name": "아이폰",
  "description": "안녕하세요 최고의 핸드폰",
  "addProductItemRequestDtos": [
    {
      "productId": 5,
      "name": "아이템1",
      "price": 1000000,
      "count": 100
    }
  ]
}


### 셀러 상품 아이템 등록
POST http://localhost:8081/seller/product/item
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0VUpLVU5CTjFabGY3QkV5N2FPZmVTYjJRWktxRGhScnl6MXl5dHZpWkUwPSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgxMTQzMTQxLCJleHAiOjE2ODExNDY3NDF9.Ek4uQP_dO5iOdHZL-6Qe6Kj6bw99v3w0zsGFLPpSdeo

{
  "productId": 4,
  "name": "아이템2",
  "price": 10000,
  "count": 100
}

### 셀러 상품 수정
PUT http://localhost:8081/seller/product
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0VUpLVU5CTjFabGY3QkV5N2FPZmVTYjJRWktxRGhScnl6MXl5dHZpWkUwPSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgxMTQzMTQxLCJleHAiOjE2ODExNDY3NDF9.Ek4uQP_dO5iOdHZL-6Qe6Kj6bw99v3w0zsGFLPpSdeo

{
  "id": 1,
  "name": "수정된 이름",
  "description": "애플이 출시한 최고의 테블릿!",
  "items":
          [
            {
              "id": 1,
              "name": "아이템2",
              "price": 200000,
              "count": 100000000
            }

          ]
}

### 셀러 상품 아이템 수정
PUT http://localhost:8081/seller/product/item
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0VUpLVU5CTjFabGY3QkV5N2FPZmVTYjJRWktxRGhScnl6MXl5dHZpWkUwPSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgxMTQzMTQxLCJleHAiOjE2ODExNDY3NDF9.Ek4uQP_dO5iOdHZL-6Qe6Kj6bw99v3w0zsGFLPpSdeo

{
  "id": 1,
  "name": "수정된 아이템1",
  "price": 100,
  "count": 1
}

### 셀러 상품 삭제
DELETE http://localhost:8081/seller/product/4
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0VUpLVU5CTjFabGY3QkV5N2FPZmVTYjJRWktxRGhScnl6MXl5dHZpWkUwPSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgxMTIxODE1LCJleHAiOjE2ODExMjU0MTV9.syChZ5pu2l78lvRpM2clEnhSId8DdStVb2T6LMhDcDM

### 셀러 상품 아이템 삭제
DELETE http://localhost:8081/seller/product/item/8
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0VUpLVU5CTjFabGY3QkV5N2FPZmVTYjJRWktxRGhScnl6MXl5dHZpWkUwPSIsImp0aSI6IlN1YkhlS1VSUnJlUVkrV1NPbkJrdGc9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgxMTQzMTQxLCJleHAiOjE2ODExNDY3NDF9.Ek4uQP_dO5iOdHZL-6Qe6Kj6bw99v3w0zsGFLPpSdeo


### 상품 조회
GET http://localhost:8081/search/product/detail/4
Content-Encoding: gzip
Transfer-Encoding: chuncked
Content-Type: application/json

### 상품 상세 조회
GET http://localhost:8081/search/product?name=아이패드
Content-Type: application/json

### 장바구니 추가
POST http://localhost:8081/customer/cart
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0VUpLVU5CTjFabGY3QkV5N2FPZmVTYjJRWktxRGhScnl6MXl5dHZpWkUwPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgxMjUwMjA1LCJleHAiOjE2ODEyNTM4MDV9.BruG-cN8WKUBaIyjJw-9NHSwmLATfm0T1EVJC3y9Q48

{
  "id": 4,
  "sellerId": 1,
  "productItems": [
    {
      "id": 1,
      "name": "아이템2",
      "price": 2000,
      "count": 100
    }
  ],
  "description": "상품 설명"
}
